#############################################################################################
###--- Setup Environment -------------------------------------------------------------------#
###############################################           #
# require libs for setup          #EEEE n   n v       v rrrr    m     m   ttttt #           #                  
require(raster)                   #E    nn  n  v     v  r   r  m m   m m    t   #           #         
require(envimaR)                  #EE   n n n   v   v   rrrr   m m   m m    t   #           #                
require(link2GI)                  #E    n  nn    v v    r  r  m   m m   m   t   #           #             
#EEEE n   n     v     r   r m    m    m   t   #           #
###############################################           #

# define needed libs and src folder                                                         #
libs = c("link2GI","reshape2","dplyr","vegan","cluster","labdsv","rgdal","stringr") 
pathdir = "R/src/"

#set root folder for uniPC or laptop                                                        #
root_folder = alternativeEnvi(root_folder = "~/edu/Envimaster-BioGeo",                      #
                              alt_env_id = "COMPUTERNAME",                                  #
                              alt_env_value = "PCRZP",                                      #
                              alt_env_root_folder = "F:/edu/Envimaster-BioGeo")             #
#source environment script                                                                  #
source(file.path(root_folder, paste0(pathdir,"000_envrmt_bio_v1.R")))                                                              
###---------------------------------------------------------------------------------------###
#############################################################################################

# compute Privot tables
# script to compute Privot tables

#load data
main <- read.csv(file.path(envrmt$path_stage2,"main_clean.csv"))
head(main)
main<- main[,-1]
# 1. prepare datasets for privot tables

# change name for epi treetyp in new df
# here the "names" for the plots can be modified to view in Ordinations
main4ep <- main
main4sub <- main
main4ep$ID <- do.call(paste0, main[c("treetyp","ID")])
main4sub$ID <- do.call(paste0, main[c("Sub","ID")])
main <- main[,-6]
main$ID <- do.call(paste0,main[c("dep_ID","ID")])

# make subtables for all substrates
SL <- subset(main,main[,2]%in% grep("SL", main[,2], value = TRUE))              
DW<- subset(main,main[,2]%in% grep("DW", main[,2], value = TRUE))  
EP  <- subset(main4ep,main4ep[,2]%in% grep("EP", main[,2], value = TRUE))  

# delet unneeded "level" and "sub" column for SL and DW
# rownames (for ordination) can be chnaged with the upper merge of columns
DW <- DW[,-2:-3]
SL <- SL[,-2:-3]

# clean up NA lvl in EP
EP <- EP[-which(is.na(EP$level)),]

# merge columns ID and Sub names to one to get acces to select Epi subplots in privot by name suffix
EP_lvl <- EP
EP_lvl$ID <- do.call(paste0, EP_lvl[c("ID","Sub")])
EP_lvl <-EP_lvl[,-2]
EP <- EP[,-2]
###########################################################################################

# 2. compute privot tables for Mainplots and aggregated Subplots


#use reshape with melt and dcast to get privot table
# use 1rst col for rownames and delet 1st col (due to factor class not supportetd by MVS)

SU_p <- dcast(main4sub,ID~spec,value.var="cover",fun.aggregate = mean)
rownames(SU_p)<-SU_p$ID
SU_p <-SU_p[,-1] 

DW_p <- dcast(DW,ID~spec,value.var="cover",fun.aggregate = sum)
rownames(DW_p)<-DW_p$ID
DW_p <-DW_p[,-1] 

SL_p <- dcast(SL,ID~spec,value.var="cover",fun.aggregate = sum)
rownames(SL_p)<-SL_p$ID
SL_p <-SL_p[,-1] 

EP_p <- dcast(EP,ID~spec,value.var="cover",fun.aggregate = mean)
rownames(EP_p)<-EP_p$ID
EP_p <-EP_p[,-1] 

MP_p <- dcast(main,ID~spec,value.var="cover",fun.aggregate = mean)
rownames(MP_p)<-MP_p$ID
MP_p <-MP_p[,-1] 

EP_lvl_p <- dcast(EP_lvl,ID~spec,value.var="cover",fun.aggregate = mean)

#clean up Na vales (generated by mean function)
EP_p[EP_p=="NaN"] <- 0
MP_p[MP_p=="NaN"] <- 0
SU_p[SU_p=="NaN"] <- 0

# 3 compute privot tables with appeariacne only

#copy org datasets
SL_c <- SL_p
DW_c <- DW_p
EP_c <- EP_p
MP_c <- MP_p
SU_c <- SU_p

# replace all values unequal 0 to 1, leaves only 1 for existing and 0 for missing
SL_c[SL_c>0] <-1
DW_c[DW_c>0] <-1
EP_c[EP_c>0] <-1
MP_c[MP_c>0] <-1
SU_c[SU_c>0] <-1

# 4. write out Privot tables for ordination
write.csv(SL_p,file.path(envrmt$path_privot,"soil_cov.csv"))
write.csv(DW_p,file.path(envrmt$path_privot,"deadwood_cov.csv"))
write.csv(EP_p,file.path(envrmt$path_privot,"epi_cov.csv"))
write.csv(MP_p,file.path(envrmt$path_privot,"mainplots_cov.csv"))
write.csv(SU_p,file.path(envrmt$path_privot,"substrates_cov.csv"))

write.csv(SL_c,file.path(envrmt$path_privot,"soil_occur.csv"))
write.csv(DW_c,file.path(envrmt$path_privot,"deadwood_occur.csv"))
write.csv(EP_c,file.path(envrmt$path_privot,"epi_occur.csv"))
write.csv(MP_c,file.path(envrmt$path_privot,"mainplots_occur.csv"))
write.csv(SU_c,file.path(envrmt$path_privot,"substrates_occur.csv"))

# 5. write out privot tables with bb scale for Species Tables

# convert numeric vales to BB scale, set " " for 0 and turn table
MP_out <-conv_num2bb(MP_p)
SU_out <-conv_num2bb(SU_p)
SL_out <-conv_num2bb(SL_p)
DW_out <-conv_num2bb(DW_p)
EP_out <-conv_num2bb(EP_p)

write.csv(MP_out,file.path(envrmt$path_stage2,"spectable_MP.csv"))
write.csv(SU_out,file.path(envrmt$path_stage2,"spectable_SU.csv"))
write.csv(SL_out,file.path(envrmt$path_stage2,"spectable_SL.csv"))
write.csv(DW_out,file.path(envrmt$path_stage2,"spectable_DW.csv"))
write.csv(EP_out,file.path(envrmt$path_stage2,"spectable_EP.csv"))
